== Database Access

We've come to the last part of the live coding portion. (hope there's time?) We're going to add some simple database
access using Jooq. I'm going to be kind of hand-wavey about jooq because there isn't time to discuss it in detail.
Basically it's a type safe way to build SQL queries.

First we need to update the build script:

....
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.h2database:h2:1.4.186'
        classpath 'org.jooq:jooq-codegen:3.8.1'
    }
}

compile ratpack.dependency('hikari')
compile 'com.h2database:h2:1.4.186'
compile 'org.jooq:jooq:3.8.1'

import org.jooq.util.jaxb.*
import org.jooq.util.*

task jooqCodegen {
    doLast {
        String init = "$projectDir/src/main/resources/init.sql".replaceAll('\\\\', '/')
        Configuration configuration = new Configuration()
                .withJdbc(new Jdbc()
                .withDriver("org.h2.Driver")
                .withUrl("jdbc:h2:mem:todo;INIT=RUNSCRIPT FROM '$init'")
        )
                .withGenerator(new Generator()
                .withDatabase(new Database()
                .withName("org.jooq.util.h2.H2Database")
                .withIncludes(".*")
                .withExcludes("")
                .withInputSchema("PUBLIC")
        )
                .withTarget(new Target()
                .withDirectory("$projectDir/src/main/java")
                .withPackageName("jooq")))
        GenerationTool.generate(configuration)
    }
}
....

init.sql

....
DROP TABLE IF EXISTS todo;
CREATE TABLE blacklist (
  `id` bigint auto_increment primary key,
  `path` varchar(256)
)
....

For demonstration purposes, we're just using an in memory h2 database. After adding the gradle task for code generation
and the "schema" then we can run gradle jooqCodegen and it will build the java classes we need. Now we can start
configuring ratpack.

....
.module(HikariModule.class, config -> {
                            config.setDataSourceClassName("org.h2.jdbcx.JdbcDataSource");
                            config.addDataSourceProperty(
                                    "URL",
                                    "jdbc:h2:mem:todo;INIT=RUNSCRIPT FROM 'classpath:/init.sql'");
                        })
....

Hikari provides a jdbc connection, and the module is configured much like any other. In this case we're manually setting
some properties instead of driving them from a properties file - but that's very similar to what we've already seen.

Now we're going to create a repository for our crud operations and a module to provide the funcitonality to the ratpack
application.

....
public class BlackListModel {
    long id;
    String host;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getHost() {
        return host;
    }

    public void setHost(String host) {
        this.host = host;
    }
}
....

....
public class BlackListRepository {
    private final DSLContext context;

    @Inject
    public BlackListRepository(DSLContext context) {
        this.context = context;
    }

    public Promise<List<BlackListModel>> getBlacklists() {
        SelectJoinStep all = context.select().from(Tables.BLACKLIST);
        return Blocking.get(() -> all.fetchInto(BlackListModel.class));
    }

    public Promise<Optional<BlackListModel>> findByHost(String host) {
        SelectConditionStep one = context.select().from(Tables.BLACKLIST).where(Tables.BLACKLIST.HOST.eq(host));
        return Blocking.get(() -> one.fetchOptionalInto(BlackListModel.class));
    }

    public Promise<BlackListModel> addBlacklistItem(BlackListModel blackListModel) {
        BlacklistRecord record = context.newRecord(Tables.BLACKLIST, blackListModel);
        return Blocking.op(record::store)
                .next(Blocking.op(record::refresh))
                .map(() -> record.into(BlackListModel.class));
    }
....

Also add the jooq module to the app. Add the blacklist handler.

....
public class BlackListHandler implements Handler {
    BlackListRepository repository;

    public BlackListHandler(BlackListRepository repository) {
        this.repository = repository;
    }

    @Override
    public void handle(Context ctx) throws Exception {
        ctx.byMethod(method -> method
                .get(() ->
                        repository.getBlacklists()
                                .map(Jackson::json)
                                .then(ctx::render)
                )
                .post(() -> {
                    Promise<BlackListModel> item = ctx.parse(Jackson.fromJson(BlackListModel.class));
                    item.flatMap(repository::addBlacklistItem).map(Jackson::json).then(ctx::render);
                })
        );
    }
}
....

Demo adding the black list and retrieving from it.

....
http http://localhost:5050/admin/blacklist
http POST http://localhost:5050/admin/blacklist host="0:0:0:0:0:0:0:1"
http http://localhost:5050/admin/blacklist
....

we use ipv6 because we're modern damnit

Now that we can do the rest thing for our black list, we will use it somewhere. this is the final piece of the demo.

....
public class RestrictHostHandler implements Handler {
    private static Logger logger = LoggerFactory.getLogger(RestrictHostHandler.class);

    @Override
    public void handle(Context ctx) throws Exception {
        BlackListRepository blackListRepository = ctx.get(BlackListRepository.class);

        String host = ctx.getRequest().getRemoteAddress().getHostText();
        logger.info("Checking blacklist for " +  host);
        blackListRepository.findByHost(host).then(blackListedHost -> {
           if (blackListedHost.isPresent()) {
               ctx.getResponse().status(403);
               ctx.getResponse().send("BLACKLISTED!");
           } else {
               ctx.next();
           }
        });
    }
}
....

wire it up and demo.

The important part here is the difference between rendering a response and calling context.next()