/**
 * This class is generated by jOOQ
 */
package jooq;


import javax.annotation.Generated;

import jooq.tables.Blacklist;
import jooq.tables.records.BlacklistRecord;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<BlacklistRecord, Long> IDENTITY_BLACKLIST = Identities0.IDENTITY_BLACKLIST;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BlacklistRecord> CONSTRAINT_F = UniqueKeys0.CONSTRAINT_F;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<BlacklistRecord, Long> IDENTITY_BLACKLIST = createIdentity(Blacklist.BLACKLIST, Blacklist.BLACKLIST.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<BlacklistRecord> CONSTRAINT_F = createUniqueKey(Blacklist.BLACKLIST, "CONSTRAINT_F", Blacklist.BLACKLIST.ID);
    }
}
